{% set name = "sparrow" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/man-group/sparrow/archive/{{ version }}.tar.gz
  sha256: 51f1da3e954d95368d1c46a386730adf6b2e98b11204e4c40d940c26d2aa80fc

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:
    - howardhinnant_date >=3,<4
  run:
    # howardhinnant_date has run_exports

test:
  commands:
    - test -f ${PREFIX}/include/sparrow/buffer/buffer.hpp                                    # [unix]
    - test -f ${PREFIX}/include/sparrow/config/sparrow_version.hpp                           # [unix]
    - test -f ${PREFIX}/share/cmake/sparrow/sparrowConfig.cmake                              # [unix]
    - test -f ${PREFIX}/share/cmake/sparrow/sparrowConfigVersion.cmake                       # [unix]
    - test -f ${PREFIX}/share/cmake/sparrow/sparrowTargets.cmake                             # [unix]
    - if not exist %LIBRARY_PREFIX%\include\sparrow\buffer\buffer.hpp (exit 1)               # [win]
    - if not exist %LIBRARY_PREFIX%\include\sparrow\config\sparrow_version.hpp (exit 1)      # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\sparrow\sparrowConfig.cmake (exit 1)         # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\sparrow\sparrowConfigVersion.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\sparrow\sparrowTargets.cmake (exit 1)        # [win]

about:
  summary: C++20 idiomatic APIs for the Apache Arrow Columnar Format
  description: C++20 idiomatic APIs for the Apache Arrow Columnar Format
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  home: https://github.com/man-group/sparrow
  dev_url: https://github.com/man-group/sparrow

extra:
  recipe-maintainers:
    - jjerphan
    - JohanMabille
    - Klaim
