{% set name = "sparrow" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xtensor-stack/sparrow/archive/{{ version }}.tar.gz
  sha256: 06f833cb3ada1f25edff912daf66c92d5ec5c8086f93bb085cb658e6f9db18d2

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/sparrow/buffer.hpp                                           # [unix]
    - test -f ${PREFIX}/include/sparrow/sparrow_version.hpp                                  # [unix]
    - test -f ${PREFIX}/share/cmake/sparrow/sparrowConfig.cmake                              # [unix]
    - test -f ${PREFIX}/share/cmake/sparrow/sparrowConfigVersion.cmake                       # [unix]
    - test -f ${PREFIX}/share/cmake/sparrow/sparrowTargets.cmake                             # [unix]
    - if not exist %LIBRARY_PREFIX%\include\sparrow\buffer.hpp (exit 1)                      # [win]
    - if not exist %LIBRARY_PREFIX%\include\sparrow\sparrow_version.hpp (exit 1)             # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\sparrow\sparrowConfig.cmake (exit 1)         # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\sparrow\sparrowConfigVersion.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\sparrow\sparrowTargets.cmake (exit 1)        # [win]

about:
  summary: C++20 idiomatic APIs for the Apache Arrow Columnar Format
  description: C++20 idiomatic APIs for the Apache Arrow Columnar Format
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  home: https://github.com/xtensor-stack/sparrow
  dev_url: https://github.com/xtensor-stack/sparrow

extra:
  recipe-maintainers:
    - jjerphan
    - JohanMabille
    - Klaim
